{
 "title": "AmneziaVPN Exporter",
 "tags": [
  "wireguard",
  "vpn",
  "networking"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(wireguard_interface_up, instance)"
    }
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "label_values(wireguard_interface_up{instance=~\"$instance\"}, interface)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Interface Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "wireguard_interface_up{instance=~\"$instance\", interface=~\"$interface\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "wireguard_interface_peers{instance=~\"$instance\", interface=~\"$interface\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "wireguard_interface_listen_port{instance=~\"$instance\", interface=~\"$interface\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Traffic Rate - Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(wireguard_peer_receive_bytes_total{instance=~\"$instance\", interface=~\"$interface\"}[5m])",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Peer Traffic Rate - Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(wireguard_peer_transmit_bytes_total{instance=~\"$instance\", interface=~\"$interface\"}[5m])",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Peer Traffic Total - Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "wireguard_peer_receive_bytes_total{instance=~\"$instance\", interface=~\"$interface\"}",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Peer Traffic Total - Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "wireguard_peer_transmit_bytes_total{instance=~\"$instance\", interface=~\"$interface\"}",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Peer Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "wireguard_peer_latest_handshake_seconds{instance=~\"$instance\", interface=~\"$interface\"} * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "wireguard_peer_receive_bytes_total{instance=~\"$instance\", interface=~\"$interface\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "wireguard_peer_transmit_bytes_total{instance=~\"$instance\", interface=~\"$interface\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}